---
- name: Install base on a workstation
  hosts: workstation
  gather_facts: false

  tasks:
  - name: add oracle_vbox_2016.asc apt-key
    apt_key: 
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
 
  - name: add oracle_vbox.asc apt-key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox.asc
      state: present

  - name: add virtualbox apt repository
    apt_repository: 
      repo: 'deb https://download.virtualbox.org/virtualbox/debian stretch contrib' 
      state: present 
      filename: virtualbox
      update_cache: yes

  - name: Install pakages
    apt: 
      install_recommends: yes
      update_cache: yes
      cache_valid_time: 3600
      state: latest
      autoclean: yes
      autoremove: yes
      name: 
      - yakuake
      - nano
      - sudo
      - atop
      - htop
      - sysstat
      - iftop
      - tcpdump
      - strace
      - dstat
      - konsole
      - mtr
      - wget
      - curl
      - lxde
      - lightdm
      - ncdu
      - git
      - wget
      - pwgen
      - udns-utils
      - screen
      - rsync
      - mc
      - virtualbox-6.1
      - pssh

  - name: Change sysctl
    sysctl:
      name: vm.swappiness
      value: '5'
      state: present
      reload: yes

  - name: Create a directory ~/.ssh if it does not exist
    file:
      path: /home/grumble/.ssh
      state: directory
      mode: 0700
      owner: grumble
      group: grumble

  - name: SSH client config   
    template:       
      src: ssh_config.j2
      dest: "/home/grumble/.ssh/config"       
      mode: 0600
      owner: grumble
      group: grumble
      backup: yes

  - name: Insert whithout password access in sudoers for grumble
    lineinfile:
      dest: /etc/sudoers
      line: 'grumble ALL=(ALL:ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'

  - name: Insert sudo alias in bashrc
    lineinfile:
      dest: /home/grumble/.bashrc
      backup: yes
      line: 'alias sd="sudo su"'
